### ISSUE TITLE
user-in-team didn't work in canary release aciton

### ISSUE THREAD

**Issue by jezdez** [conda/actions#14]
I'm just filing this to make sure we look into why it didn't work when I tried the user-in-team action:

<img width="802" alt="CleanShot 2022-02-03 at 12 01 49@2x" src="https://user-images.githubusercontent.com/1610/152330674-8b1196d5-e657-482e-a200-5007f467d27b.png">

Here's the workflow: https://github.com/conda/conda/runs/5026079866?check_suite_focus=true

And here the code how I used it (in this case where I removed it again to work-around it): https://github.com/conda/conda/pull/11195

**Comment by kenodegard** [comment]
I suspect this was a permissions thing, the default `GITHUB_TOKEN` is not enough to read from the org level. It is very unfortunate that we cannot use the [`permissions` key](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) in our workflows for this...

**Comment by jezdez** [comment]
> I suspect this was a permissions thing, the default `GITHUB_TOKEN` is not enough to read from the org level. It is very unfortunate that we cannot use the [`permissions` key](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) in our workflows for this...

Oooh, interesting, I hadn't thought of that, not sure how to fix this, expand the token? Use a separate one?

**Comment by kenodegard** [comment]
We'll need to define another org secret with the correct personal access token scope. I don't know what policy we want for when a new token/secret should be defined. Currently I've sought to have a unique token/secret per GitHub workflow, less permission bleed between workflows.
