### ISSUE TITLE
Create new release to be useable for osx-arm64 aka Apple Silicon Runners

### ISSUE THREAD

**Issue by dbast** [conda/actions#151]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The canary release action was already updated to setup-miniconda@v3 (compatible with Apple Silicon Runners) via https://github.com/conda/actions/pull/141 but no release was done since then.

### What should happen?

A release to be tagged.

**Comment by jezdez** [comment]
Done! https://github.com/conda/actions/releases/tag/v24.2.0
